### PR TITLE
Translations and contribute notification

### PR DESCRIPTION
**Pull request by leon-wbr**
Hi,

There is now a translation for three languages available and we can translate on top of that. See http://learnbitcoinfast.com for the current version, there's also a corresponding repository.

I don't know what caused so many posts to be considered edited. They weren't, I suppose it is because I moved them between directories once, but decided not to as this caused permalinks to be skewed.

Please verify the functionality yourself, as I can't guarantee that my testing was valid. I might have missed things.

There's also a merge conflict.

### CODE REVIEW

**Comment by sunnankar** [comment]
@bobgle It shows this branch has conflicts to resolve before it can be merged. Can you perhaps get it fixed up before merging on the main site?

I took at look at the test and there were issues with relative links for images and such also. So, it looks like there might be some refining for you to do before it is ready.

**Comment by bobgle** [comment]
@sunnankar  I'll see if I can do that.

Think you can give me some examples? It makes sense that relative images wouldn't work anymore, but I did not notice that happening anywhere.

**Comment by leon-wbr** [comment]
I fixed the merge. I still need more information on what issues you've noticed.

**Comment by sunnankar** [comment]
@leon-wbr I think it is working better.

**Pull request merged**
