### PR TITLE
Added Social Share Buttons

### PR DESCRIPTION
**Pull request by bobgle**
Maybe this needs a .gitignore

### CODE REVIEW

**Comment by sunnankar** [comment]
@bobgle Is there anyway you can reduce the number of file changes? It seems like the commit is unnecessarily complex with 130 file changes and I need to be able to quickly review the diffs. Thanks.

**Comment by bobgle** [comment]
Should be fixed now. It shows 9 changed files for me, which is correct.

**Comment by sunnankar** [comment]
@bobgle It got the price and volume but there are no social sharing buttons showing up. I moved the include in the default layout but it did not fix the issue. Anyway you can fix it up so it is like WUC's? Thanks.

**Comment by sunnankar** [comment]
@bobgle Oh, looks like it may have been a cache issue. The sharing buttons came up. However, the Diff. has not loaded; same problem on WUC. I wonder if it is a local problem with cache?

Anyway you can look at that?

Thanks.

**Comment by bobgle** [comment]
@sunnankar For me, the diff is loading fine. I assume it is a local caching problem, but I can't guarantee. I've cleared mine, it is still working. If you're able to provide me with some more information I might be able to take a closer look at it but for now I would suggest you to clear your cache once again or rebuild the site (but I assume this is not necessary).

**Comment by sunnankar** [comment]
I think it is some type of local caching problem. I think it may have to do with the Diff. value not changing and therefore it does not get loaded. Annoying but not sure there is much we can do about it.

**Comment by bobgle** [comment]
I actually just had the issue of it not loading as well, but it was fixed with a reload. There seems to be some inconsistency or sometimes an issue with connecting to the API which provides this functionality. It does seem reliable enough, though and is pretty subtle when encountering an error.

**Pull request merged**
