### PR TITLE
Small mistakes correction

### PR DESCRIPTION
**Pull request by kweros**
Sorry, sunnankar. 
I've noticed two sentences not translated to Portuguese and a "</center>" lost in the text.
I've corrected everything!
How should I proceed to get US$15 in my wallet? My address is: 17ogKnyxvULowRzFc82aUtLanWXrwVjo15
Tks!

### CODE REVIEW

**Comment by kweros** [comment]
I would like to know how should I proceed to participate on Slack channel.
Can you contact me by email to learn me?

**Comment by sunnankar** [comment]
Thanks for the fix. BTC sent.

**Comment by sunnankar** [comment]
The Slack channel is not very active currently so I would not worry about trying to join it.

**Comment by kweros** [comment]
Ok, tks!

Enviado do meu iPhone

Em 28 de jul de 2018, à(s) 19:55, sunnankar <notifications@github.com> escreveu:

**Comment by kweros** [comment]
Sunnakar,
If you have "infographic png files templates", I could translate it as
well. Or maybe, I can send you a "table from-to English-Portuguese" with
infographic texts to help with translation. How do you prefer?

I would like to translate more pages for Portuguese. Can I get English
"htm files" and create pull requests with Portuguese files in PT directory?

*Roberto Gomes*


Em sáb, 28 de jul de 2018 às 21:40, Roberto Gomes <robertomgomes@gmail.com>
escreveu:

**Pull request merged**
