### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by leon-wbr**
Half a page (getting started) for now, but still wanted to submit to finish up this week. Files look very good with Markdown.

### CODE REVIEW

**Comment by sunnankar** [comment]
@leon-wbr Making sure to use the latest pages for the source, right?

**Comment by leon-wbr** [comment]
@sunnankar I assume most of them are site-specific (so WUC has different sources), so the latest ones are the English versions on BM? If so, I did.

**Comment by sunnankar** [comment]
Yes. I think the WUC Getting Started page has been significantly updated since it was last copied into the various language directories.

**Comment by leon-wbr** [comment]
But I think BM's getting started was focused on Mining whereas WUC is general getting started with Bitcoin. I took the English source from BM for the translation.

**Pull request merged**
